In [1]:
from em_analysis import EMAnalysis

sensor_id = 12345
path = rf'C:\Users\emili\OneDrive\Documents\Projects\VenaVitals\zaber-python\12345\02 03 26_325mm2_EB_A\FUT'
sensor_type = int("3")

# Create analysis instance
analysis = EMAnalysis(path, sensor_id, sensor_type)

# Get results
result = analysis.save_data()

# from shear_analysis import ShearAnalysis
# shear_id = 67
# path = rf'C:\Users\emili\OneDrive\Documents\Projects\VenaVitals\zaber-python\67\11 24 25_50.27_SHEAR\FUT'
# shear_analysis = ShearAnalysis(path, shear_id)
# result = shear_analysis.run_full_analysis()


C:\Users\emili\OneDrive\Documents\Projects\VenaVitals\zaber-python\12345\02 03 26_325mm2_EB_A
C:\Users\emili\OneDrive\Documents\Projects\VenaVitals\zaber-python\12345\02 03 26_325mm2_EB_A\CAP
[0.    0.016 0.032 0.048 0.064]
[0.         0.01013184 0.02029419 0.03045654 0.04058838]
[0.    0.016 0.032 0.048 0.064]
[0.         0.01013184 0.02029419 0.03045654 0.0406189 ]
[0.    0.016 0.032 0.048 0.064]
[0.         0.01016235 0.02032471 0.03048706 0.0406189 ]
13.522845460026423 ,  0.22692124795546545
9.872322224561819 ,  0.3808426452905235
9.478322026418004 ,  0.3120131282983815
7.623077863636319 ,  0.4017604976807752
7.008749000887764 ,  0.4324892567243048
6.266719510567391 ,  0.45282980176861537
6.013146151309039 ,  0.467228827669044
11.805254721335405 ,  0.1925947315095219
---
12.576151050487555 ,  0.2064010209838457
9.122959640986728 ,  0.3997106827067703
7.917910438861865 ,  0.41779389510315684
7.213728932476977 ,  0.4925059396679298
6.50771131779329 ,  0.47960293003188986
5.8284468955

c:\Users\emili\OneDrive\Documents\Projects\VenaVitals\zaber-python\em_analysis.py:322: RuntimeWarning: divide by zero encountered in divide
  fir_dev_ij = np.diff(y_smooth) / np.diff(x_smooth)


12.844098114762376 ,  0.22988875002773393
8.9828918002646 ,  0.39874546240784864
7.638671381742556 ,  0.43044474189723436
7.294959244766145 ,  0.47143411209850233
6.582912208523193 ,  0.4811077815072991
6.026852587568463 ,  0.4777193868498528
6.370492298544803 ,  0.35083974085101854
9.072483664368328 ,  0.24754020422884
---
Processing run 1/3...
Processing run 2/3...
Processing run 3/3...


In [2]:
for value in result['max_kpa']:
    for value2 in value:
        print(value2)
    print('---')

# for value in result['mean_max_kpa']:
#     print(value)

13.522845460026423
9.872322224561819
9.478322026418004
7.623077863636319
11.805254721335405
6.013146151309039
6.266719510567391
7.008749000887764
---
12.576151050487555
9.122959640986728
7.917910438861865
7.213728932476977
7.857811935217899
6.156016875893935
5.828446895565128
6.50771131779329
---
12.844098114762376
8.9828918002646
7.638671381742556
7.294959244766145
9.072483664368328
6.370492298544803
6.026852587568463
6.582912208523193
---


In [ ]:
# Check FUT data for NaN values
import numpy as np

i = 0
fut_data = analysis.run[i][1]

print(f"FUT data stats:")
print(f"  Shape: {fut_data.shape}")
print(f"  Min: {np.nanmin(fut_data):.6f}")
print(f"  Max: {np.nanmax(fut_data):.6f}")
print(f"  NaN count: {np.sum(np.isnan(fut_data))}")

# Find the indices of NaN values
nan_indices = np.where(np.isnan(fut_data))[0]
print(f"\nNaN locations:")
if len(nan_indices) > 0:
    print(f"  First NaN at index: {nan_indices[0]}")
    print(f"  Last NaN at index: {nan_indices[-1]}")
    print(f"  Total NaN indices: {len(nan_indices)}")
    
# The argmax of an array with NaN usually returns the index of the first element
# But if the max is NaN, it might return something weird
loc_f = np.argmax(fut_data)
print(f"\nArgmax of FUT:")
print(f"  Index: {loc_f}")
print(f"  Value: {fut_data[loc_f]}")

# Try with nanmax instead
loc_f_nanmax = np.nanargmax(fut_data)
print(f"\nNanargmax of FUT:")
print(f"  Index: {loc_f_nanmax}")
print(f"  Value: {fut_data[loc_f_nanmax]}")

# Check what the real max force should be
print(f"\nFUT data range (excluding NaN):")
valid_fut = fut_data[~np.isnan(fut_data)]
print(f"  Min: {valid_fut.min():.6f}, Max: {valid_fut.max():.6f}")
print(f"  Peak at index: {np.argmax(valid_fut)}")
print(f"  Peak value: {valid_fut.max():.6f}")


FUT data stats:
  Shape: (26865,)
  Min: -0.160563
  Max: 32.195632
  NaN count: 4

NaN locations:
  First NaN at index: 26861
  Last NaN at index: 26864
  Total NaN indices: 4

Argmax of FUT:
  Index: 26861
  Value: nan

Nanargmax of FUT:
  Index: 25837
  Value: 32.19563195921164

FUT data range (excluding NaN):
  Min: -0.160563, Max: 32.195632
  Peak at index: 25837
  Peak value: 32.195632


In [4]:
for value in result['max_ps']:
    for value2 in value:
        print(value2)
    print('---')

0.21708682443382574
0.348410831462523
0.2904385092201231
0.3560044401387427
0.3627976896537741
0.37797269297535147
0.38617676391868117
0.1814284532923408
---
0.20857630361076862
0.3680730495619602
0.37709488826660315
0.46068989535430366
0.46520321740111614
0.4686266937684174
0.3247567763615701
0.22674512607949587
---
0.21027145797915428
0.3326923642566557
0.3642952466016318
0.4067830542650048
0.4325982940663691
0.40489982228645005
0.3052951994540721
0.2088176392014942
---


In [9]:
# The v=5 parameter means it starts extracting from column 5
# But maybe the actual CAP data (change values) are in different columns?
# Let me check the _correct_ch_order logic

print("Channel order correction:")
print(f"sensor_type: {analysis.sensor_type}")
print(f"ch_order: {analysis.ch_order}")
print(f"v (version): {analysis.v}")

cols = (
    list(range(0, 5)) +
    list(analysis.ch_order + analysis.v - 1) +
    list(range(13, 16))
)
print(f"Selected column indices: {cols}")
print(f"So the reordered dataframe will use:")
print(f"  Cols 0-4: original cols {list(range(0, 5))}")
print(f"  Cols 5-12 (CAP): original cols {list(analysis.ch_order + analysis.v - 1)}")
print(f"  Cols 13-15: original cols {list(range(13, 16))}")

print(f"\nThen in _interp_cap(), it extracts columns starting at v={analysis.v}:")
print(f"  col_idx = j + v, so j=0..7 gives col_idx = 5..12")
print(f"  These should be the 8 CAP channels")

# Let's compare what MATLAB might be using
print(f"\nIn MATLAB code from user:")
print(f"  zaber_y{{i,j}} = smooth(y(st_pt:end),100);")
print(f"  This reads the y data for channel j")
print(f"  User said raw values in MATLAB are ~2.5x higher than Python")

# Check the ratio
print(f"\nActual CAP value ratio check:")
print(f"  Column 5 (absolute): 24.37")
print(f"  Column 13 (change?): -0.0183")
print(f"  Column 14 (change?): 0.0029")
print(f"  Column 15 (change?): -0.9975")
print(f"\nRatio of col5 to col15: {24.37 / 0.9975:.1f}x (not 2.5x though)")


Channel order correction:
sensor_type: 3
ch_order: [1 2 3 4 8 7 6 5]
v (version): 5
Selected column indices: [0, 1, 2, 3, 4, np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(12), np.int64(11), np.int64(10), np.int64(9), 13, 14, 15]
So the reordered dataframe will use:
  Cols 0-4: original cols [0, 1, 2, 3, 4]
  Cols 5-12 (CAP): original cols [np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(12), np.int64(11), np.int64(10), np.int64(9)]
  Cols 13-15: original cols [13, 14, 15]

Then in _interp_cap(), it extracts columns starting at v=5:
  col_idx = j + v, so j=0..7 gives col_idx = 5..12
  These should be the 8 CAP channels

In MATLAB code from user:
  zaber_y{i,j} = smooth(y(st_pt:end),100);
  This reads the y data for channel j
  User said raw values in MATLAB are ~2.5x higher than Python

Actual CAP value ratio check:
  Column 5 (absolute): 24.37
  Column 13 (change?): -0.0183
  Column 14 (change?): 0.0029
  Column 15 (change?): -0.9975

Ratio of col5 to col15:

In [4]:
# Check if the range constraint is working
from scipy.signal import savgol_filter
import numpy as np

i = 0
j = 0

k = np.where(analysis.test[i][1][:,1] - analysis.start_force > 0)[0][0]
f = np.where(analysis.test[i][1][:,1] - analysis.end_force > 0)[0][0]

x = analysis.test[i][1][k:f, 1]  
y = analysis.test[i][0][k:f, j+1]

st_pt = np.where(x-0 > 0)[0][0]

x_smooth = savgol_filter(x[st_pt:], 101, 2)
y_smooth = savgol_filter(y[st_pt:], 101, 2)

fir_dev = np.diff(y_smooth) / np.diff(x_smooth)
fir_dev[(fir_dev > 1) | (fir_dev < 0)] = 0

# Check range constraint
search_min = 5
search_max = 40
valid_mask = (x_smooth >= search_min) & (x_smooth <= search_max)
valid_indices = np.where(valid_mask)[0]

print(f"x_smooth shape: {x_smooth.shape}")
print(f"fir_dev shape: {fir_dev.shape}")
print(f"Valid force indices: {len(valid_indices)} points")
print(f"First valid index: {valid_indices[0] if len(valid_indices) > 0 else 'None'}")
print(f"Last valid index: {valid_indices[-1] if len(valid_indices) > 0 else 'None'}")
if len(valid_indices) > 0:
    print(f"x_smooth[valid_indices[0:5]]: {x_smooth[valid_indices[0:5]]}")
    print(f"fir_dev[valid_indices[0:5]]: {fir_dev[valid_indices[0:5]]}")

    # Max in valid range
    valid_deriv = fir_dev[valid_indices]
    max_valid_idx_local = np.argmax(valid_deriv)
    max_valid_idx = valid_indices[max_valid_idx_local]
    print(f"\nMax in range: {fir_dev[max_valid_idx]:.6f}")
    print(f"Force at max in range: {x_smooth[max_valid_idx]:.6f}")
    print(f"MATLAB expected: ~12.5 kPa")

Number of peaks found: 1
Peak 0: index=20128, value=0.204591, force=22.473888

Peaks in valid range (5-40 kPa): 1
Valid peak 0: index=20128, value=0.204591, force=22.473888


Number of peaks found: 1
Peak 0: index=20128, value=0.204591, force=22.473888

Peaks in valid range (5-40 kPa): 1
Valid peak 0: index=20128, value=0.204591, force=22.473888


C:\Users\emili\AppData\Local\Temp\ipykernel_62132\993273915.py:20: RuntimeWarning: divide by zero encountered in divide
  fir_dev = np.diff(y_smooth) / np.diff(x_smooth)
